//! User-visible strings, in Chinese and English.
//!
//! The catalog is generated by one macro invocation so the enum, both language
//! tables and the parity tests all come from a single list — the two languages
//! cannot drift apart, and a missing translation is a compile error.
//!
//! Note the distinction between two languages:
//!
//! * **UI language** (`lang`) — which catalog is used. The user can force it.
//! * **Text locale** (`dwrite_locale`) — handed to DirectWrite for every run of
//!   text. This always follows the *system* locale regardless of the UI choice:
//!   it drives font fallback and line breaking, so a Japanese title must be laid
//!   out with a Japanese locale even when the menus are in English.

use std::sync::atomic::{AtomicU8, Ordering};
use std::sync::OnceLock;
use windows::{core::PCWSTR, Win32::Globalization::GetUserDefaultLocaleName};

macro_rules! strings {
    ($($key:ident => $zh:expr, $en:expr;)*) => {
        /// Every user-visible string in the program.
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        #[repr(usize)]
        pub enum Key { $($key),* }

        impl Key {
            /// All keys in declaration order. Used by the catalog tests.
            pub const ALL: &'static [Key] = &[$(Key::$key),*];
        }

        const ZH: &[&str] = &[$($zh),*];
        const EN: &[&str] = &[$($en),*];
    };
}

strings! {
    // ---- card ---------------------------------------------------------------
    Loading                 => "正在加载…",                      "Loading…";
    NotPlaying              => "未在播放",                        "Not playing";
    UnknownTrack            => "未知曲目",                        "Unknown track";
    StatusNoLibrary         => "未设置音乐目录 · 右键选择",        "No music folder · right-click to choose";
    StatusScanning          => "正在扫描音乐库…",                  "Scanning your library…";
    StatusEmptyLibrary      => "这个位置没有音乐文件",             "No music files in that location";
    StatusMissingDirs       => "音乐目录不存在",                   "Music folder is missing";
    StatusNoAudioDevice     => "没有可用的音频设备",               "No audio output device";
    StatusWaitingAudio      => "正在等待音频设备…",                "Waiting for the audio device…";

    // ---- tray --------------------------------------------------------------
    TrayTip                 => "DesktopMusicWidget",              "DesktopMusicWidget";
    TrayNoAudioTitle        => "没有可用的音频设备",               "No audio output device";
    TrayNoAudioText         => "播放将在设备可用后开始。",          "Playback will start once a device is available.";
    TrayEmptyTitle          => "没有找到音乐",                     "No music found";
    TrayEmptyText           => "右键托盘图标可以重新选择音乐目录。", "Right-click the tray icon to choose another folder.";
    TrayLegacyTitle         => "检测到旧版自启动项",               "Legacy autostart entry found";
    TrayLegacyText          => "设置里可以移除它，避免开机启动两个版本。", "You can remove it in Settings so only one version starts.";

    // ---- menu --------------------------------------------------------------
    MenuPlay                => "播放",                            "Play";
    MenuPause               => "暂停",                            "Pause";
    MenuPrev                => "上一首",                          "Previous track";
    MenuNext                => "下一首",                          "Next track";
    MenuPlayMode            => "播放模式",                        "Play mode";
    PlayModeSequential      => "顺序播放",                        "In order";
    PlayModeShuffle         => "随机播放",                        "Shuffle";
    PlayModeRepeatOne       => "单曲循环",                        "Repeat one";
    MenuLibrary             => "音乐目录",                        "Music folders";
    MenuAddFolder           => "添加文件夹…",                     "Add folder…";
    MenuReplaceFolder       => "替换为…",                         "Replace with…";
    MenuOpenFolder          => "打开第一个目录",                   "Open first folder";
    MenuClearFolders        => "清空",                            "Clear";
    MenuScan                => "扫描选项",                        "Scan options";
    MenuScanRecursive       => "包含子文件夹",                     "Include subfolders";
    MenuExcludeFolder       => "排除文件夹…",                     "Exclude folder…";
    MenuRescan              => "重新扫描音乐库",                   "Rescan library";
    MenuAutostart           => "开机自启动",                      "Start with Windows";
    MenuAutoplay            => "启动时自动播放",                   "Play on launch";
    MenuShowControls        => "显示控制按钮",                     "Show controls";
    ShowControlsHover       => "悬停时显示",                       "On hover";
    ShowControlsAlways      => "始终显示",                        "Always";
    MenuZOrder              => "窗口层级",                        "Window layer";
    ModeBottom              => "桌面层（推荐）",                   "Desktop layer (recommended)";
    ModeTopmost             => "置顶显示",                        "Always on top";
    MenuMonitor             => "显示器",                          "Monitor";
    MonitorItem             => "显示器 {}",                        "Monitor {}";
    MenuMoveWindow          => "移动窗口（拖动）",                 "Move window (drag)";
    MenuSettings            => "设置…",                           "Settings…";
    MenuOpenConfig          => "打开配置文件",                     "Open config file";
    MenuReloadConfig        => "重新加载配置",                     "Reload config";
    MenuAbout               => "关于 DesktopMusicWidget",          "About DesktopMusicWidget";
    MenuExit                => "退出",                            "Exit";

    // ---- dialogs & messages ------------------------------------------------
    DlgPickFolderTitle      => "选择音乐文件夹",                   "Choose music folders";
    DlgPickExcludeTitle     => "选择要排除的文件夹",               "Choose a folder to exclude";
    DlgFirstRunTitle        => "欢迎使用 DesktopMusicWidget",      "Welcome to DesktopMusicWidget";
    DlgFirstRunText         => "先选择存放音乐的文件夹，可以多选。\n选好后会立刻显示找到了多少首。",
                               "Pick the folders that hold your music — you can select several.\nThe number of tracks found is shown right away.";
    DlgFoundTitle           => "扫描结果",                        "Scan result";
    DlgFoundText            => "已找到 {} 首音乐文件。\n\n开始使用吗？",
                               "Found {} music files.\n\nStart using them?";
    DlgFoundNoneText        => "这些位置没有找到音乐文件。\n\n可以重新选择，也可以先保留当前设置。",
                               "No music files were found in those locations.\n\nYou can pick again, or keep the current settings.";
    DlgConfigBadTitle       => "配置文件读不出来",                 "Config file could not be read";
    DlgConfigBadText        => "原文件已备份为 config.toml.bak，本次先使用默认设置。",
                               "The original was backed up to config.toml.bak; defaults are in use for now.";
    DlgConfigSavedText      => "设置已保存。",                     "Settings saved.";
    DlgOpenConfigFailedTitle=> "打不开配置文件",                   "Could not open the config file";
    DlgOpenConfigFailedText => "请手动打开：\n{}",                  "Please open it manually:\n{}";
    DlgFolderMissingTitle   => "目录不存在",                       "Folder not found";
    DlgFolderMissingText    => "这个目录已经不存在了：\n{}",        "That folder no longer exists:\n{}";
    DlgAboutTitle           => "关于 DesktopMusicWidget",          "About DesktopMusicWidget";
    DlgAboutText            => "DesktopMusicWidget {}\n构建目标：{}\n\n配置文件：\n{}\n\n日志文件：\n{}\n\nMIT 协议 · {}",
                               "DesktopMusicWidget {}\nBuild target: {}\n\nConfig file:\n{}\n\nLog file:\n{}\n\nMIT licensed · {}";
    DlgConfirmRemoveLegacyTitle => "移除旧版自启动项",              "Remove legacy autostart entry";
    DlgConfirmRemoveLegacyText  => "将删除注册表里的 HorizMusicWidget 自启动项（旧版）。\n当前程序的设置不受影响。",
                                   "This deletes the legacy HorizMusicWidget autostart entry.\nThe current app's settings are not affected.";
    DlgHintTitle            => "DesktopMusicWidget",              "DesktopMusicWidget";
    DlgMoveModeOn           => "移动模式：拖动卡片到想要的位置，松手即保存。\n再按一次菜单里的“移动窗口”可退出移动模式。",
                               "Move mode: drag the card where you want it, and it is saved on release.\nChoose “Move window” again to leave move mode.";

    // ---- settings window ---------------------------------------------------
    SetTitle                => "DesktopMusicWidget 设置",          "DesktopMusicWidget Settings";
    SetGroupFolders         => "音乐目录",                        "Music folders";
    SetAdd                  => "添加…",                           "Add…";
    SetRemove               => "移除",                            "Remove";
    SetOpen                 => "打开",                            "Open";
    SetGroupScan            => "扫描范围",                        "Scan scope";
    SetRecursive            => "包含子文件夹",                     "Include subfolders";
    SetExcludes             => "排除的文件夹（按名称或完整路径）",  "Excluded folders (by name or full path)";
    SetFound                => "已找到 {} 首音乐文件",             "Found {} music files";
    SetScanning             => "正在扫描…",                        "Scanning…";
    SetNoLibrary            => "还没有添加音乐目录",               "No music folder added yet";
    SetGroupStartup         => "启动与播放",                      "Startup & playback";
    SetPlayMode             => "播放模式",                        "Play mode";
    SetVolume               => "音量",                            "Volume";
    SetGroupAppearance      => "外观与位置",                      "Appearance & position";
    SetWidth                => "宽度",                            "Width";
    SetHeight               => "高度",                            "Height";
    SetCorners              => "圆角",                            "Corner radius";
    SetOpacity              => "不透明度",                        "Opacity";
    SetShowControls         => "控制按钮",                        "Controls";
    SetZOrder               => "窗口层级",                        "Window layer";
    SetMonitor              => "显示器",                          "Monitor";
    SetFont                 => "字体",                            "Font";
    SetGroupGeneral         => "通用",                            "General";
    SetLanguage             => "界面语言",                        "Language";
    LangAuto                => "跟随系统",                        "Follow system";
    // Language names are shown in their own language in both catalogs, which is
    // what users expect from a language picker.
    LangZh                  => "中文",                            "中文";
    LangEn                  => "English",                         "English";
    SetHotkeys              => "启用全局快捷键",                   "Enable global hotkeys";
    SetHotkeyPreset         => "快捷键方案",                      "Hotkey preset";
    HotkeyPresetCtrlAlt     => "Ctrl+Alt+方向键 / 空格",           "Ctrl+Alt+arrows / Space";
    HotkeyPresetCtrlShiftAlt=> "Ctrl+Shift+Alt+方向键 / 空格",     "Ctrl+Shift+Alt+arrows / Space";
    SetHotkeyFailed         => "部分快捷键已被其他程序占用",        "Some hotkeys are taken by another app";
    SetHotkeyOk             => "快捷键已生效",                     "Hotkeys registered";
    SetRestoreDefaults      => "恢复默认",                        "Restore defaults";
    SetCancel               => "取消",                            "Cancel";
    SetApply                => "应用",                            "Apply";
    SetOk                   => "确定",                            "OK";
    SetPathInfo             => "配置文件：{}",                     "Config file: {}";
    SetRemoveLegacy         => "移除旧版自启动项",                 "Remove legacy autostart";
    SetInvalidNumber        => "请填写有效数字（{}）",             "Please enter a valid number ({})";
    SetRestartHint          => "部分设置需要重启后生效",            "Some settings apply after a restart";
}

impl Key {
    fn index(self) -> usize {
        self as usize
    }
}

/// Which catalog is in use.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Lang {
    Zh,
    En,
}

static CURRENT: AtomicU8 = AtomicU8::new(0);
static SYSTEM: AtomicU8 = AtomicU8::new(0);
static LOCALE_W: OnceLock<Vec<u16>> = OnceLock::new();

/// The locale name Windows reports for the current user, e.g. `zh-CN`, `ja-JP`.
/// Falls back to `en-US` when the API fails.
pub fn system_locale_name() -> String {
    unsafe {
        // LOCALE_NAME_MAX_LENGTH is 85.
        let mut buf = [0u16; 85];
        let n = GetUserDefaultLocaleName(&mut buf);
        if n > 1 {
            return String::from_utf16_lossy(&buf[..(n as usize - 1)]);
        }
    }
    "en-US".to_string()
}

fn lang_from_locale(name: &str) -> Lang {
    let lower = name.to_ascii_lowercase();
    if lower.starts_with("zh") {
        Lang::Zh
    } else {
        Lang::En
    }
}

/// Resolves the language to use and installs it. Call once during startup.
///
/// `choice` is the raw `language` config value: `auto`, `zh-CN` or `en`.
/// Returns the language actually selected.
pub fn init(choice: &str) -> Lang {
    let system = lang_from_locale(&system_locale_name());
    SYSTEM.store(
        match system {
            Lang::Zh => 0,
            Lang::En => 1,
        },
        Ordering::Relaxed,
    );

    let lang = match choice {
        "zh-CN" | "zh" => Lang::Zh,
        "en" | "en-US" => Lang::En,
        _ => system,
    };
    set_lang(lang);
    lang
}

pub fn set_lang(lang: Lang) {
    CURRENT.store(
        match lang {
            Lang::Zh => 0,
            Lang::En => 1,
        },
        Ordering::Relaxed,
    );
}

pub fn current() -> Lang {
    if CURRENT.load(Ordering::Relaxed) == 1 {
        Lang::En
    } else {
        Lang::Zh
    }
}

/// The system language, ignoring any user override.
pub fn system_lang() -> Lang {
    if SYSTEM.load(Ordering::Relaxed) == 1 {
        Lang::En
    } else {
        Lang::Zh
    }
}

/// The config value that reproduces the current UI language.
pub fn current_choice() -> &'static str {
    match current() {
        Lang::Zh => "zh-CN",
        Lang::En => "en",
    }
}

pub fn tr(key: Key) -> &'static str {
    match current() {
        Lang::Zh => ZH[key.index()],
        Lang::En => EN[key.index()],
    }
}

/// Substitutes `{}` placeholders in order. Extra arguments are ignored and a
/// missing argument leaves the placeholder empty, so this never panics.
pub fn tr_fmt(key: Key, args: &[&str]) -> String {
    let template = tr(key);
    let mut out = String::with_capacity(template.len() + 32);
    let mut parts = template.split("{}");
    if let Some(first) = parts.next() {
        out.push_str(first);
    }
    for (i, part) in parts.enumerate() {
        if let Some(arg) = args.get(i) {
            out.push_str(arg);
        }
        out.push_str(part);
    }
    out
}

/// `tr_fmt` for the common single-number case.
pub fn tr_num(key: Key, n: usize) -> String {
    tr_fmt(key, &[&n.to_string()])
}

/// The locale handed to DirectWrite for text layout. Always the system locale:
/// this drives font fallback, so it must not follow the UI language override.
pub fn dwrite_locale() -> PCWSTR {
    let buf = LOCALE_W.get_or_init(|| {
        let mut w: Vec<u16> = system_locale_name().encode_utf16().collect();
        w.push(0);
        w
    });
    PCWSTR(buf.as_ptr())
}

#[cfg(test)]
mod tests {
    use super::*;
    // The catalog keys are enum variants; bring them in unqualified for the
    // assertions below.
    use super::Key::*;
    use std::sync::Mutex;

    /// The current language is process-global, so any test that changes it has to
    /// hold this lock or it will race the other one.
    static LANG_LOCK: Mutex<()> = Mutex::new(());

    fn lock_lang() -> std::sync::MutexGuard<'static, ()> {
        LANG_LOCK.lock().unwrap_or_else(|e| e.into_inner())
    }

    #[test]
    fn catalogs_have_matching_lengths() {
        assert_eq!(ZH.len(), Key::ALL.len(), "zh table is out of sync");
        assert_eq!(EN.len(), Key::ALL.len(), "en table is out of sync");
    }

    #[test]
    fn no_translation_is_empty() {
        for (i, key) in Key::ALL.iter().enumerate() {
            assert!(!ZH[i].is_empty(), "{key:?} has no Chinese text");
            assert!(!EN[i].is_empty(), "{key:?} has no English text");
        }
    }

    #[test]
    fn locale_detection_handles_chinese_variants() {
        assert_eq!(lang_from_locale("zh-CN"), Lang::Zh);
        assert_eq!(lang_from_locale("zh-Hans-CN"), Lang::Zh);
        assert_eq!(lang_from_locale("zh-TW"), Lang::Zh);
        assert_eq!(lang_from_locale("en-US"), Lang::En);
        assert_eq!(lang_from_locale("ja-JP"), Lang::En);
        assert_eq!(lang_from_locale(""), Lang::En);
    }

    #[test]
    fn explicit_choice_overrides_detection() {
        let _guard = lock_lang();
        assert_eq!(init("zh-CN"), Lang::Zh);
        assert_eq!(init("en"), Lang::En);
        // Anything unrecognised falls back to the system language.
        assert_eq!(init("klingon"), system_lang());
    }

    #[test]
    fn formatting_substitutes_in_order() {
        let _guard = lock_lang();
        set_lang(Lang::En);
        assert_eq!(tr_num(SetFound, 42), "Found 42 music files");
        assert_eq!(
            tr_fmt(MonitorItem, &["2"]),
            "Monitor 2",
            "single placeholder"
        );
        // Missing arguments must not panic.
        set_lang(Lang::Zh);
        assert_eq!(tr_fmt(MonitorItem, &[]), "显示器 ");
    }

    #[test]
    fn dwrite_locale_is_null_terminated() {
        let p = dwrite_locale();
        // `as_wide` stops before the terminator, so check the raw byte after it.
        let s = unsafe { p.as_wide() };
        assert!(!s.is_empty(), "locale must not be empty");
        let byte_after = unsafe { *p.as_ptr().add(s.len()) };
        assert_eq!(byte_after, 0, "locale must be NUL terminated");
    }
}
